### ISSUE TITLE
Compiling ahk does not work, but exe does

### ISSUE THREAD

**Issue by ghost** [chrisma/Hearthstone-Hotkeys#1]
Hey, I can run your exe fine, but when I compile the ahk script the commands don't work. Have you noticed this too?

**Comment by ghost** [comment]
I think I figured out the problem, you must use the latest build of Autohotkey L because the normal version of autohotkey doesn't support returning an array of objects from a function... "return [AbsoluteX, AbsoluteY]" does not work with vanilla ahk as far as I can tell

**Comment by chrisma** [comment]
Hello,
thanks for your feedback! Sorry for not getting back to you earlier.
Yes, [Autohotkey_L](https://github.com/Lexikos/AutoHotkey_L) aka [Autohotkey 1.1.*](http://ahkscript.org/download/) is needed as it provides [additional features](http://maul-esel.github.io/ahkbook/en/What-Version-To-Choose.html), such as arrays. It is a fork of the original [Autohotkey](https://github.com/AutoHotkey/AutoHotkey) which unfortunately hasn't seen any updates since 2009.
I have updated that information in the README.
