### ISSUE TITLE
Some shortcuts are not working

### ISSUE THREAD

**Issue by JorgeMadson** [chrisma/Hearthstone-Hotkeys#8]
Hi, i am new to autohotkey, but i found you project and it awesome!
I have tried it about 5 minutes ago, and some commands are not working.
Ctrl+W is not atacking with all minions, only one and pass the turn.
Ctrl+Esc is not auto conceding.
I think some layout maybe be changed from two years or its because my HS is in portuguese.

Anyway, great job! I am really surprise with your script!
Thank you!

**Comment by chrisma** [comment]
Hi Jorge,
thanks! 

The `Ctrl+w` hotkey has unfortunately always been a bit hit-and-miss, mostly because it repeatedly scans the board for a green border around minions, which indicates that they are able to attack. This highlighting isn't constant, so there can be problems. `Ctrl+w` is really more something I wanted to try out, using the `Ctrl+a`shortcut will not pass the turn automatically.

The fact that your HS is in a different language could definitely cause the menu interactions to fail. The script relies on knowledge where the buttons are on the screen.
I'll see if I can change my HS's langauge to test this.
